/**
 * Generate development routes for isolated component testing
 */

import { join } from "@std/path";
import type { SprigComponent } from "../parser/mod.ts";
import { parseDevProps, mergeDevProps } from "../parser/dev-props.ts";
import type { TranspilerConfig } from "../config/transpiler-config.ts";

export interface GeneratedDevRoute {
  /** Output path relative to dist/ */
  outputPath: string;
  /** Generated TSX content */
  content: string;
  /** Component name */
  componentName: string;
}

/**
 * Convert a component name to a URL-safe slug
 */
function toSlug(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Generate a dev route for a single component
 */
export async function generateDevRoute(
  component: SprigComponent,
  config: TranspilerConfig,
): Promise<GeneratedDevRoute> {
  const componentName = component.metadata.className;
  const slug = toSlug(componentName);

  // Parse mod.json if exists
  const modJsonProps = await parseDevProps(component.path);

  // Merge with defaults from @Input
  const devProps = mergeDevProps(modJsonProps, component.inputs);

  // Generate props object as code
  const propsCode = JSON.stringify(devProps.props, null, 4);

  // Determine import path
  const folder = component.metadata.island ? "islands" : "components";
  const importPath = `@/${folder}/${componentName}.tsx`;

  const content = `/**
 * Development route for ${componentName}
 * Auto-generated by Sprig transpiler
 */

import { define } from "@/utils.ts";
import ${componentName} from "${importPath}";

export default define.page(function Dev${componentName}() {
  const devProps = ${propsCode.replace(/\n/g, "\n  ")};

  return (
    <div class="dev-container" style="padding: 2rem; font-family: system-ui;">
      <header style="margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 1px solid #ddd;">
        <h1 style="margin: 0 0 0.5rem;">${componentName}</h1>
        <p style="color: #666; margin: 0;">
          Development preview | <a href="${config.devRoutePrefix}">Back to Index</a>
        </p>
      </header>

      <main style="padding: 1rem; border: 1px dashed #ccc; border-radius: 4px;">
        <${componentName} {...devProps} />
      </main>

      <footer style="margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #ddd;">
        <details>
          <summary style="cursor: pointer; color: #666;">View Props</summary>
          <pre style="background: #f5f5f5; padding: 1rem; overflow: auto; margin-top: 0.5rem;">
{JSON.stringify(devProps, null, 2)}
          </pre>
        </details>
      </footer>
    </div>
  );
});
`;

  const outputPath = `routes/${config.devRoutesPath}/${slug}/index.tsx`;

  return { outputPath, content, componentName };
}

/**
 * Generate the dev routes index page
 */
export function generateDevIndex(
  components: SprigComponent[],
  config: TranspilerConfig,
): { outputPath: string; content: string } {
  const componentLinks = components.map((c) => {
    const slug = toSlug(c.metadata.className);
    const hasInputs = c.inputs.length > 0;
    const inputCount = c.inputs.length;
    const isIsland = c.metadata.island;

    return `        <li style="margin-bottom: 0.5rem;">
          <a href="${config.devRoutePrefix}/${slug}" style="color: #0066cc; text-decoration: none;">
            ${c.metadata.className}
          </a>
          ${isIsland ? '<span style="background: #e8f5e9; color: #2e7d32; padding: 0.125rem 0.375rem; border-radius: 3px; font-size: 0.75rem; margin-left: 0.5rem;">Island</span>' : ""}
          ${hasInputs ? `<span style="color: #999; font-size: 0.875rem;"> (${inputCount} prop${inputCount !== 1 ? "s" : ""})</span>` : ""}
        </li>`;
  }).join("\n");

  const content = `/**
 * Development Routes Index
 * Auto-generated by Sprig transpiler
 */

import { define } from "@/utils.ts";

export default define.page(function DevIndex() {
  return (
    <div class="dev-index" style="padding: 2rem; font-family: system-ui; max-width: 800px; margin: 0 auto;">
      <header style="margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 2px solid #333;">
        <h1 style="margin: 0 0 0.5rem;">Component Development</h1>
        <p style="color: #666; margin: 0;">
          Isolated development environment for testing components
        </p>
      </header>

      <main>
        <h2 style="margin-top: 0;">Components ({${components.length}})</h2>
        <ul style="list-style: none; padding: 0;">
${componentLinks}
        </ul>
      </main>

      <footer style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #999; font-size: 0.875rem;">
        <p>Generated by Sprig Transpiler</p>
      </footer>
    </div>
  );
});
`;

  const outputPath = `routes/${config.devRoutesPath}/index.tsx`;

  return { outputPath, content };
}

/**
 * Write all dev routes to disk
 */
export async function writeDevRoutes(
  components: SprigComponent[],
  config: TranspilerConfig,
  outDir: string,
): Promise<void> {
  // Filter to only domain components (not layouts, routes, or special files)
  // Layouts have relativePath starting with _ (e.g., _app, _error)
  const devComponents = components.filter((c) =>
    c.type === "component" && !c.relativePath.startsWith("_")
  );

  if (devComponents.length === 0) {
    return;
  }

  // Create dev routes directory
  const devDir = join(outDir, "routes", config.devRoutesPath);
  await Deno.mkdir(devDir, { recursive: true });

  // Generate and write index
  const index = generateDevIndex(devComponents, config);
  const indexPath = join(outDir, index.outputPath);
  await Deno.writeTextFile(indexPath, index.content);

  // Generate and write component routes
  for (const component of devComponents) {
    const route = await generateDevRoute(component, config);
    const routePath = join(outDir, route.outputPath);
    const routeDir = routePath.replace(/[/\\][^/\\]+$/, "");

    await Deno.mkdir(routeDir, { recursive: true });
    await Deno.writeTextFile(routePath, route.content);
  }
}
