/**
 * Runtime helper functions for pipes
 * These functions are used by transformed pipe expressions
 */

/**
 * Convert string to title case
 * @example toTitleCase("hello world") => "Hello World"
 */
export function toTitleCase(value: string): string {
  if (!value) return "";
  return value
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/**
 * Format a number as currency
 * @param value - The numeric value to format
 * @param currencyCode - ISO 4217 currency code (default: 'USD')
 * @param locale - Locale for formatting (default: 'en-US')
 */
export function formatCurrency(
  value: number,
  currencyCode: string = "USD",
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: currencyCode,
  }).format(value);
}

/**
 * Format a date value
 * @param value - Date value (Date object, string, or number)
 * @param format - Format string: 'short', 'medium', 'long', 'full', or custom pattern
 * @param locale - Locale for formatting (default: 'en-US')
 */
export function formatDate(
  value: Date | string | number,
  format: string = "medium",
  locale: string = "en-US",
): string {
  if (!value) return "";

  const date = value instanceof Date ? value : new Date(value);

  if (isNaN(date.getTime())) return "";

  const formatMap: Record<string, Intl.DateTimeFormatOptions> = {
    short: { year: "numeric", month: "numeric", day: "numeric" },
    medium: { year: "numeric", month: "short", day: "numeric" },
    long: { year: "numeric", month: "long", day: "numeric" },
    full: { weekday: "long", year: "numeric", month: "long", day: "numeric" },
    shortTime: { hour: "numeric", minute: "numeric" },
    mediumTime: { hour: "numeric", minute: "numeric", second: "numeric" },
    shortDateTime: {
      year: "numeric",
      month: "numeric",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    },
  };

  const options = formatMap[format] || formatMap.medium;
  return new Intl.DateTimeFormat(locale, options).format(date);
}

/**
 * Format a number with specific decimal places
 * @param value - The numeric value to format
 * @param format - Format string like '1.2-2' (minInt.minFrac-maxFrac)
 * @param locale - Locale for formatting (default: 'en-US')
 */
export function formatNumber(
  value: number,
  format: string = "1.0-3",
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";

  // Parse format string: minIntegerDigits.minFractionDigits-maxFractionDigits
  const match = format.match(/^(\d+)\.(\d+)-(\d+)$/);

  if (!match) {
    // Fallback to default formatting
    return new Intl.NumberFormat(locale).format(value);
  }

  const [, minIntegerDigits, minFractionDigits, maxFractionDigits] = match;

  return new Intl.NumberFormat(locale, {
    minimumIntegerDigits: parseInt(minIntegerDigits, 10),
    minimumFractionDigits: parseInt(minFractionDigits, 10),
    maximumFractionDigits: parseInt(maxFractionDigits, 10),
  }).format(value);
}

/**
 * Format a number as a percentage
 * @param value - The numeric value (0-1 for 0%-100%, or actual percentage)
 * @param locale - Locale for formatting (default: 'en-US')
 */
export function formatPercent(
  value: number,
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";

  return new Intl.NumberFormat(locale, {
    style: "percent",
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value);
}

/**
 * Generate the import statement for pipe helpers
 */
export function generatePipeHelpersImport(helpers: string[]): string {
  if (helpers.length === 0) return "";
  return `import { ${helpers.join(", ")} } from "@/utils/pipes.ts";\n`;
}

/**
 * Generate the complete pipe helpers file content
 */
export function generatePipeHelpersFile(): string {
  return `/**
 * Runtime helper functions for pipes
 * Auto-generated by Sprig transpiler
 */

export function toTitleCase(value: string): string {
  if (!value) return "";
  return value
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function formatCurrency(
  value: number,
  currencyCode: string = "USD",
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: currencyCode,
  }).format(value);
}

export function formatDate(
  value: Date | string | number,
  format: string = "medium",
  locale: string = "en-US",
): string {
  if (!value) return "";
  const date = value instanceof Date ? value : new Date(value);
  if (isNaN(date.getTime())) return "";

  const formatMap: Record<string, Intl.DateTimeFormatOptions> = {
    short: { year: "numeric", month: "numeric", day: "numeric" },
    medium: { year: "numeric", month: "short", day: "numeric" },
    long: { year: "numeric", month: "long", day: "numeric" },
    full: { weekday: "long", year: "numeric", month: "long", day: "numeric" },
  };

  const options = formatMap[format] || formatMap.medium;
  return new Intl.DateTimeFormat(locale, options).format(date);
}

export function formatNumber(
  value: number,
  format: string = "1.0-3",
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";
  const match = format.match(/^(\\d+)\\.(\\d+)-(\\d+)$/);
  if (!match) return new Intl.NumberFormat(locale).format(value);

  const [, minInt, minFrac, maxFrac] = match;
  return new Intl.NumberFormat(locale, {
    minimumIntegerDigits: parseInt(minInt, 10),
    minimumFractionDigits: parseInt(minFrac, 10),
    maximumFractionDigits: parseInt(maxFrac, 10),
  }).format(value);
}

export function formatPercent(
  value: number,
  locale: string = "en-US",
): string {
  if (value == null || isNaN(value)) return "";
  return new Intl.NumberFormat(locale, {
    style: "percent",
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value);
}
`;
}
